// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PurAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace PurAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(PurDbContext))]
    [Migration("20251104021758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PurAnalyzer.Domain.Parsing.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ba_code");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("comment");

                    b.Property<string>("ContractorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contractor_code");

                    b.Property<string>("ContractorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contractor_name");

                    b.Property<int?>("DocumentDayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("document_day_number");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_number");

                    b.Property<DateTime?>("ExternalDocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("external_document_date");

                    b.Property<string>("ExternalDocumentNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_document_number");

                    b.Property<string>("Flag1")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flag1");

                    b.Property<string>("Flag2")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flag2");

                    b.Property<string>("Flag3")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flag3");

                    b.Property<decimal?>("GrossTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_total");

                    b.Property<decimal?>("NetTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_total");

                    b.Property<DateTime?>("OperationDate")
                        .HasColumnType("date")
                        .HasColumnName("operation_date");

                    b.Property<string>("Type")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type");

                    b.Property<decimal?>("VatTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("vat_total");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("BaCode", "Type", "DocumentNumber", "OperationDate")
                        .HasDatabaseName("ix_documents_ba_code_type_document_number_operation_date");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("PurAnalyzer.Domain.Parsing.DocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AverageAfter")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("average_after");

                    b.Property<decimal?>("AverageBefore")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("average_before");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal?>("NetValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_value");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductGroup")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("product_group");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("QuantityAfter")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_after");

                    b.Property<decimal?>("QuantityBefore")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_before");

                    b.Property<decimal?>("UnitPriceNet")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price_net");

                    b.Property<decimal?>("VatValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("vat_value");

                    b.HasKey("Id")
                        .HasName("pk_document_items");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_items_document_id");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("PurAnalyzer.Domain.Parsing.DocumentItem", b =>
                {
                    b.HasOne("PurAnalyzer.Domain.Parsing.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_items_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PurAnalyzer.Domain.Parsing.Document", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
